#ifndef RBRBRBR_HEADER_GUARD_RBRBRBR
#define RBRBRBR_HEADER_GUARD_RBRBRBR

namespace RBRBRBR_NAMESPACE_NAME_RBRBRBR {
namespace RBRBRBR_MODULE_NAME_RBRBRBR {

int pause(int p_value = 0) ;

} // namespace RBRBRBR_MODULE_NAME_RBRBRBR
} // namespace RBRBRBR_NAMESPACE_NAME_RBRBRBR

#endif // RBRBRBR_HEADER_GUARD_RBRBRBR

