#include <RBRBRBR_NAMESPACE_NAME_RBRBRBR.RBRBRBR_MODULE_NAME_RBRBRBR/main.hpp>
#include <iostream>

#define NOMINMAX
#include <windows.h>

int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, INT)
{
   return RBRBRBR_NAMESPACE_NAME_RBRBRBR::RBRBRBR_MODULE_NAME_RBRBRBR::pause(0) ;
}

namespace RBRBRBR_NAMESPACE_NAME_RBRBRBR {
namespace RBRBRBR_MODULE_NAME_RBRBRBR {

int pause(int p_value)
{
   MessageBox(NULL, "Press OK to continue...", "RBRBRBR_NAMESPACE_NAME_RBRBRBR::RBRBRBR_MODULE_NAME_RBRBRBR", MB_OK);
   return p_value ;
}

} // namespace RBRBRBR_MODULE_NAME_RBRBRBR
} // namespace RBRBRBR_NAMESPACE_NAME_RBRBRBR

