RBRBRBR_MAIN_FILE_HEADER_INCLUDE_RBRBRBR
#include <iostream>
RBRBRBR_MAIN_FILE_SFML_INCLUDE_RBRBRBR
RBRBRBR_MAIN_FILE_GTEST_INCLUDE_RBRBRBR


RBRBRBR_WINMAIN_REDIRECTOR_TO_MAIN_RBRBRBR


int main(int p_argc, char * p_argv[])
{
RBRBRBR_MAIN_FUNCTION_BODY_RBRBRBR
}