#ifndef RBRBRBR_MAIN_FILE_HEADER_GUARD_RBRBRBR
#define RBRBRBR_MAIN_FILE_HEADER_GUARD_RBRBRBR

// VCPROJ public include directory: RBRBRBR_MAIN_FILE_PUBLIC_INCLUDE_DIRECTORY_RBRBRBR

#if defined(_MSC_VER)

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT                                  __declspec(dllexport)
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT                                  __declspec(dllimport)

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXTERN
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXTERN              __declspec(dllimport)

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXTERN     __declspec(dllexport)
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXTERN     __declspec(NON_SENSICAL) // nonsensical: Template explicit instanciation should happen in one and only one .cpp file, and thus, this cannot be imported. If this happen, then you have a problem.

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXPLICIT            __declspec(dllexport)
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXPLICIT            __declspec(dllimport)

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT   __declspec(dllexport)
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT   __declspec(NON_SENSICAL) // nonsensical: Template explicit instanciation should happen in one and only one .cpp file, and thus, this cannot be imported. If this happen, then you have a problem.

#elif defined(__GNUC__)

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT                                  __attribute__ ((visibility ("default")))
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT                                  __attribute__ ((visibility ("default")))

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXTERN              __attribute__ ((visibility ("default")))
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXTERN              __attribute__ ((visibility ("default")))

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXTERN
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXTERN

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXPLICIT            __attribute__ ((visibility ("default")))
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXPLICIT            __attribute__ ((visibility ("default")))

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT

#elif defined(__clang__)

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT                                  __attribute__ ((visibility ("default")))
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT                                  __attribute__ ((visibility ("default")))

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXTERN              __attribute__ ((visibility ("default")))
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXTERN              __attribute__ ((visibility ("default")))

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXTERN
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXTERN

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXPLICIT            __attribute__ ((visibility ("default")))
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXPLICIT            __attribute__ ((visibility ("default")))

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT

#else

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXTERN
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXTERN

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXTERN
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXTERN

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXPLICIT
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXPLICIT

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT

#endif


#if defined(RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_EXPORTS)

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API                                      RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_FOR_TEMPLATE_EXTERN                  RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXTERN
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_FOR_TEMPLATE_EXPLICIT                RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXTERN
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_FOR_TEMPLATE_FUNCTION_EXTERN         RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_EXPLICIT
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_FOR_TEMPLATE_FUNCTION_EXPLICIT       RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_EXPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT

#else

#pragma comment(lib, "RBRBRBR_MAIN_FILE_PUBLIC_COMENT_LIB_RBRBRBR.lib")

#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API                                      RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_FOR_TEMPLATE_EXTERN                  RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXTERN
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_FOR_TEMPLATE_EXPLICIT                RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXTERN
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_FOR_TEMPLATE_FUNCTION_EXTERN         RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_EXPLICIT
#define RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_FOR_TEMPLATE_FUNCTION_EXPLICIT       RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API_IMPORT_FOR_TEMPLATE_FUNCTION_EXPLICIT

#endif


namespace RBRBRBR_MODULE_CPP_NAMESPACE_RBRBRBR {

RBRBRBR_MODULE_MACRO_PREFIX_RBRBRBR_x_API int get_value(int p_value);

} // namespace RBRBRBR_MODULE_CPP_NAMESPACE_RBRBRBR


#endif // RBRBRBR_MAIN_FILE_HEADER_GUARD_RBRBRBR
